// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mengbin92/browser/internal/biz"
	"mengbin92/browser/internal/conf"
	"mengbin92/browser/internal/data"
	"mengbin92/browser/internal/server"
	"mengbin92/browser/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, auth *conf.Auth, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	accountRepo := data.NewAccountRepo(dataData, logger, auth)
	accountUsecase := biz.NewAccountUsecase(accountRepo, logger)
	browserService := service.NewBrowserService(accountUsecase, logger)
	blockService := service.NewBlockService()
	grpcServer := server.NewGRPCServer(confServer, browserService, blockService, logger)
	httpServer := server.NewHTTPServer(confServer, browserService, blockService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
