// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.2
// source: browser/v1/block.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParseRequest_BlockOperation int32

const (
	ParseRequest_BLOCK        ParseRequest_BlockOperation = 0
	ParseRequest_HEADER       ParseRequest_BlockOperation = 1
	ParseRequest_DATA         ParseRequest_BlockOperation = 2
	ParseRequest_CONFIG       ParseRequest_BlockOperation = 3
	ParseRequest_CHAINCODE    ParseRequest_BlockOperation = 4
	ParseRequest_ACTIONS      ParseRequest_BlockOperation = 5
	ParseRequest_TRANSACTION  ParseRequest_BlockOperation = 6
	ParseRequest_INPUT        ParseRequest_BlockOperation = 7
	ParseRequest_RWSET        ParseRequest_BlockOperation = 8
	ParseRequest_CHANNEL      ParseRequest_BlockOperation = 9
	ParseRequest_ENDORSEMENTS ParseRequest_BlockOperation = 10
	ParseRequest_CREATOR      ParseRequest_BlockOperation = 11
	ParseRequest_METADATA     ParseRequest_BlockOperation = 12
)

// Enum value maps for ParseRequest_BlockOperation.
var (
	ParseRequest_BlockOperation_name = map[int32]string{
		0:  "BLOCK",
		1:  "HEADER",
		2:  "DATA",
		3:  "CONFIG",
		4:  "CHAINCODE",
		5:  "ACTIONS",
		6:  "TRANSACTION",
		7:  "INPUT",
		8:  "RWSET",
		9:  "CHANNEL",
		10: "ENDORSEMENTS",
		11: "CREATOR",
		12: "METADATA",
	}
	ParseRequest_BlockOperation_value = map[string]int32{
		"BLOCK":        0,
		"HEADER":       1,
		"DATA":         2,
		"CONFIG":       3,
		"CHAINCODE":    4,
		"ACTIONS":      5,
		"TRANSACTION":  6,
		"INPUT":        7,
		"RWSET":        8,
		"CHANNEL":      9,
		"ENDORSEMENTS": 10,
		"CREATOR":      11,
		"METADATA":     12,
	}
)

func (x ParseRequest_BlockOperation) Enum() *ParseRequest_BlockOperation {
	p := new(ParseRequest_BlockOperation)
	*p = x
	return p
}

func (x ParseRequest_BlockOperation) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParseRequest_BlockOperation) Descriptor() protoreflect.EnumDescriptor {
	return file_browser_v1_block_proto_enumTypes[0].Descriptor()
}

func (ParseRequest_BlockOperation) Type() protoreflect.EnumType {
	return &file_browser_v1_block_proto_enumTypes[0]
}

func (x ParseRequest_BlockOperation) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParseRequest_BlockOperation.Descriptor instead.
func (ParseRequest_BlockOperation) EnumDescriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{2, 0}
}

type UploadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Content []byte `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UploadRequest) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result bool   `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetResult() bool {
	if x != nil {
		return x.Result
	}
	return false
}

func (x *UploadResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ParseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Operation ParseRequest_BlockOperation `protobuf:"varint,2,opt,name=operation,proto3,enum=api.browser.v1.ParseRequest_BlockOperation" json:"operation,omitempty"`
}

func (x *ParseRequest) Reset() {
	*x = ParseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseRequest) ProtoMessage() {}

func (x *ParseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseRequest.ProtoReflect.Descriptor instead.
func (*ParseRequest) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{2}
}

func (x *ParseRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParseRequest) GetOperation() ParseRequest_BlockOperation {
	if x != nil {
		return x.Operation
	}
	return ParseRequest_BLOCK
}

type ParseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ParseResponse) Reset() {
	*x = ParseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParseResponse) ProtoMessage() {}

func (x *ParseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParseResponse.ProtoReflect.Descriptor instead.
func (*ParseResponse) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{3}
}

func (x *ParseResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type Endorser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MSP  string `protobuf:"bytes,1,opt,name=MSP,proto3" json:"MSP,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
}

func (x *Endorser) Reset() {
	*x = Endorser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endorser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorser) ProtoMessage() {}

func (x *Endorser) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorser.ProtoReflect.Descriptor instead.
func (*Endorser) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{4}
}

func (x *Endorser) GetMSP() string {
	if x != nil {
		return x.MSP
	}
	return ""
}

func (x *Endorser) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Endorsers struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Endorsers []*Endorser `protobuf:"bytes,1,rep,name=endorsers,proto3" json:"endorsers,omitempty"`
}

func (x *Endorsers) Reset() {
	*x = Endorsers{}
	if protoimpl.UnsafeEnabled {
		mi := &file_browser_v1_block_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Endorsers) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endorsers) ProtoMessage() {}

func (x *Endorsers) ProtoReflect() protoreflect.Message {
	mi := &file_browser_v1_block_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endorsers.ProtoReflect.Descriptor instead.
func (*Endorsers) Descriptor() ([]byte, []int) {
	return file_browser_v1_block_proto_rawDescGZIP(), []int{5}
}

func (x *Endorsers) GetEndorsers() []*Endorser {
	if x != nil {
		return x.Endorsers
	}
	return nil
}

var File_browser_v1_block_proto protoreflect.FileDescriptor

var file_browser_v1_block_proto_rawDesc = []byte{
	0x0a, 0x16, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x72,
	0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x0d, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x3c, 0x0a, 0x0e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xaa, 0x02, 0x0a, 0x0c, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x49, 0x0a, 0x09, 0x6f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xba, 0x01, 0x0a, 0x0e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x0a, 0x05, 0x42, 0x4c, 0x4f, 0x43, 0x4b, 0x10,
	0x00, 0x12, 0x0a, 0x0a, 0x06, 0x48, 0x45, 0x41, 0x44, 0x45, 0x52, 0x10, 0x01, 0x12, 0x08, 0x0a,
	0x04, 0x44, 0x41, 0x54, 0x41, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x43, 0x4f, 0x4e, 0x46, 0x49,
	0x47, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x43, 0x48, 0x41, 0x49, 0x4e, 0x43, 0x4f, 0x44, 0x45,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x53, 0x10, 0x05, 0x12,
	0x0f, 0x0a, 0x0b, 0x54, 0x52, 0x41, 0x4e, 0x53, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x06,
	0x12, 0x09, 0x0a, 0x05, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x07, 0x12, 0x09, 0x0a, 0x05, 0x52,
	0x57, 0x53, 0x45, 0x54, 0x10, 0x08, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x48, 0x41, 0x4e, 0x4e, 0x45,
	0x4c, 0x10, 0x09, 0x12, 0x10, 0x0a, 0x0c, 0x45, 0x4e, 0x44, 0x4f, 0x52, 0x53, 0x45, 0x4d, 0x45,
	0x4e, 0x54, 0x53, 0x10, 0x0a, 0x12, 0x0b, 0x0a, 0x07, 0x43, 0x52, 0x45, 0x41, 0x54, 0x4f, 0x52,
	0x10, 0x0b, 0x12, 0x0c, 0x0a, 0x08, 0x4d, 0x45, 0x54, 0x41, 0x44, 0x41, 0x54, 0x41, 0x10, 0x0c,
	0x22, 0x23, 0x0a, 0x0d, 0x50, 0x61, 0x72, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x30, 0x0a, 0x08, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x53, 0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x53, 0x50, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x43, 0x0a, 0x09, 0x45, 0x6e, 0x64, 0x6f, 0x72,
	0x73, 0x65, 0x72, 0x73, 0x12, 0x36, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x72,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x72,
	0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65,
	0x72, 0x52, 0x09, 0x65, 0x6e, 0x64, 0x6f, 0x72, 0x73, 0x65, 0x72, 0x73, 0x32, 0xd5, 0x01, 0x0a,
	0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x65, 0x0a, 0x0b, 0x55, 0x70, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x77,
	0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x62, 0x72, 0x6f, 0x77, 0x73,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x3a, 0x01, 0x2a, 0x22,
	0x0c, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x75, 0x70, 0x12, 0x65, 0x0a,
	0x0a, 0x50, 0x61, 0x72, 0x73, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x1c, 0x2e, 0x61, 0x70,
	0x69, 0x2e, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72,
	0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x61, 0x72, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14,
	0x3a, 0x01, 0x2a, 0x22, 0x0f, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x70,
	0x61, 0x72, 0x73, 0x65, 0x42, 0x25, 0x5a, 0x23, 0x6d, 0x65, 0x6e, 0x67, 0x62, 0x69, 0x6e, 0x39,
	0x32, 0x2f, 0x62, 0x72, 0x6f, 0x77, 0x73, 0x65, 0x72, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x62, 0x72,
	0x6f, 0x77, 0x73, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_browser_v1_block_proto_rawDescOnce sync.Once
	file_browser_v1_block_proto_rawDescData = file_browser_v1_block_proto_rawDesc
)

func file_browser_v1_block_proto_rawDescGZIP() []byte {
	file_browser_v1_block_proto_rawDescOnce.Do(func() {
		file_browser_v1_block_proto_rawDescData = protoimpl.X.CompressGZIP(file_browser_v1_block_proto_rawDescData)
	})
	return file_browser_v1_block_proto_rawDescData
}

var file_browser_v1_block_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_browser_v1_block_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_browser_v1_block_proto_goTypes = []interface{}{
	(ParseRequest_BlockOperation)(0), // 0: api.browser.v1.ParseRequest.BlockOperation
	(*UploadRequest)(nil),            // 1: api.browser.v1.UploadRequest
	(*UploadResponse)(nil),           // 2: api.browser.v1.UploadResponse
	(*ParseRequest)(nil),             // 3: api.browser.v1.ParseRequest
	(*ParseResponse)(nil),            // 4: api.browser.v1.ParseResponse
	(*Endorser)(nil),                 // 5: api.browser.v1.Endorser
	(*Endorsers)(nil),                // 6: api.browser.v1.Endorsers
}
var file_browser_v1_block_proto_depIdxs = []int32{
	0, // 0: api.browser.v1.ParseRequest.operation:type_name -> api.browser.v1.ParseRequest.BlockOperation
	5, // 1: api.browser.v1.Endorsers.endorsers:type_name -> api.browser.v1.Endorser
	1, // 2: api.browser.v1.Block.UpChaincode:input_type -> api.browser.v1.UploadRequest
	3, // 3: api.browser.v1.Block.ParseBlock:input_type -> api.browser.v1.ParseRequest
	2, // 4: api.browser.v1.Block.UpChaincode:output_type -> api.browser.v1.UploadResponse
	4, // 5: api.browser.v1.Block.ParseBlock:output_type -> api.browser.v1.ParseResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_browser_v1_block_proto_init() }
func file_browser_v1_block_proto_init() {
	if File_browser_v1_block_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_browser_v1_block_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_v1_block_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UploadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_v1_block_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_v1_block_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_v1_block_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endorser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_browser_v1_block_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Endorsers); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_browser_v1_block_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_browser_v1_block_proto_goTypes,
		DependencyIndexes: file_browser_v1_block_proto_depIdxs,
		EnumInfos:         file_browser_v1_block_proto_enumTypes,
		MessageInfos:      file_browser_v1_block_proto_msgTypes,
	}.Build()
	File_browser_v1_block_proto = out.File
	file_browser_v1_block_proto_rawDesc = nil
	file_browser_v1_block_proto_goTypes = nil
	file_browser_v1_block_proto_depIdxs = nil
}
