server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  tls:
    enable: false
    cert: xxxx/xxx.cert
    key: xxx/xxxx/xx.key

log:
  # 支持debug(-1)、info(0)、warn(1)、error(2)、dpanic(3)、panic(4)、fatal(5)
  level: 2
  # json or console
  format: console